name: Multiplexus
favicon: null
layout_spectrum: 0.2855125602800399
typography_spectrum: 0.7693965148646384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.39503099699504673
  lightness: 0.8776024994440377
  saturation: 0.5655273920856416
  rhythmicContrast: 0.6778949284926057
purpose: []
